CREATE TABLE lease_termination_applications (
    id VARCHAR(36) NOT NULL COMMENT '主键ID',
    application_no VARCHAR(32) NOT NULL COMMENT '退租申请编号',
    tenant_id VARCHAR(36) NOT NULL COMMENT '租客用户ID',
    contract_id VARCHAR(36) NOT NULL COMMENT '合同ID',
    house_id VARCHAR(36) NOT NULL COMMENT '房源ID',
    room_id VARCHAR(36) DEFAULT NULL COMMENT '房间ID',
    reason VARCHAR(500) NOT NULL COMMENT '退租原因',
    expected_move_out_date DATE NOT NULL COMMENT '期望退租日期',
    has_moved_out TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已搬离',
    contact_name VARCHAR(100) NOT NULL COMMENT '联系人姓名',
    contact_phone VARCHAR(20) NOT NULL COMMENT '联系人手机号',
    remark VARCHAR(1000) DEFAULT NULL COMMENT '备注',
    attachments JSON DEFAULT NULL COMMENT '附件列表',
    status VARCHAR(32) NOT NULL DEFAULT 'pending_review' COMMENT '状态：pending_review待审核, need_supplement待补充材料, approved审核通过, inspection_pending待验房, settlement_pending待结算, refund_pending待退款, completed已完成, rejected已驳回, cancelled已撤销',
    reject_reason VARCHAR(1000) DEFAULT NULL COMMENT '驳回原因',
    supplement_reason VARCHAR(1000) DEFAULT NULL COMMENT '要求补充材料原因',
    audit_user_id VARCHAR(36) DEFAULT NULL COMMENT '审核人ID',
    audit_time DATETIME DEFAULT NULL COMMENT '审核时间',
    cancel_reason VARCHAR(1000) DEFAULT NULL COMMENT '撤销原因',
    cancel_time DATETIME DEFAULT NULL COMMENT '撤销时间',
    inspection_result JSON DEFAULT NULL COMMENT '验房结果',
    inspection_completed_time DATETIME DEFAULT NULL COMMENT '验房完成时间',
    settlement_detail JSON DEFAULT NULL COMMENT '结算明细',
    total_deduction INT DEFAULT 0 COMMENT '总扣款(分)',
    refund_amount INT DEFAULT 0 COMMENT '应退金额(分)',
    settlement_confirmed_time DATETIME DEFAULT NULL COMMENT '结算确认时间',
    refund_completed_time DATETIME DEFAULT NULL COMMENT '退款完成时间',
    actual_move_out_date DATE DEFAULT NULL COMMENT '实际搬离日期',
    completed_time DATETIME DEFAULT NULL COMMENT '退租完成时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_application_no (application_no),
    KEY idx_contract_status (contract_id, status),
    KEY idx_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='退租申请表';

CREATE TABLE lease_termination_logs (
    id VARCHAR(36) NOT NULL COMMENT '主键ID',
    application_id VARCHAR(36) NOT NULL COMMENT '退租申请ID',
    action VARCHAR(32) NOT NULL COMMENT '操作类型：applied提交申请, approved审核通过, rejected驳回, supplement_requested要求补充材料, supplemented补充材料, cancelled撤销, inspection_completed验房完成, settlement_confirmed结算确认, refund_completed退款完成',
    from_status VARCHAR(32) DEFAULT NULL COMMENT '原状态',
    to_status VARCHAR(32) NOT NULL COMMENT '新状态',
    operator_id VARCHAR(36) DEFAULT NULL COMMENT '操作人ID',
    operator_name VARCHAR(100) DEFAULT NULL COMMENT '操作人姓名',
    remark VARCHAR(1000) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_application_id (application_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='退租操作日志表';
