ALTER TABLE smart_locks
    MODIFY COLUMN house_id VARCHAR(36) NULL COMMENT '绑定的房源ID，初始化后未绑定房源时为空',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'INIT_LOCAL_SUCCESS' COMMENT '门锁初始化/绑定状态：INIT_LOCAL_SUCCESS本地初始化成功，ROOM_BOUND已绑定房间，PLATFORM_BINDING同步中，PLATFORM_BOUND平台已同步，BOUND已完成绑定，PLATFORM_FAILED平台同步失败，DISABLED已禁用，UNBOUND已解绑';
