CREATE TABLE user_real_name_auth (
    id                   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    user_id              VARCHAR(36)     NOT NULL COMMENT '平台用户ID',
    real_name_auth_no    VARCHAR(64)     NOT NULL COMMENT '平台实名认证业务流水号',
    esign_face_flow_id   VARCHAR(64)     NULL COMMENT 'e签宝人脸认证流程ID',
    esign_psn_id         VARCHAR(64)     NULL COMMENT 'e签宝V3个人账号标识',
    auth_status          VARCHAR(20)     NOT NULL COMMENT 'UNVERIFIED/VERIFYING/VERIFIED/FAILED/EXPIRED/CANCELED',
    real_name            VARCHAR(100)    NOT NULL COMMENT '实名姓名',
    account_mobile       VARCHAR(32)     NULL COMMENT '平台绑定手机号',
    verified_mobile      VARCHAR(32)     NULL COMMENT '已核验手机号',
    id_card_type         VARCHAR(64)     NOT NULL COMMENT '个人证件类型',
    id_card_ciphertext   TEXT            NOT NULL COMMENT '加密后的完整证件号码',
    id_card_masked       VARCHAR(32)     NOT NULL COMMENT '脱敏证件号码',
    auth_url             TEXT            NULL COMMENT 'e签宝临时H5认证地址',
    auth_url_expire_time DATETIME        NULL COMMENT '认证地址过期时间',
    failure_code         VARCHAR(64)     NULL COMMENT '失败业务码',
    failure_message      VARCHAR(500)    NULL COMMENT '脱敏后的失败原因',
    verified_at          DATETIME        NULL COMMENT '认证完成时间',
    created_at           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version              INT             NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_real_name_auth_no (real_name_auth_no),
    UNIQUE KEY uk_esign_face_flow_id (esign_face_flow_id),
    KEY idx_user_id (user_id),
    KEY idx_user_status (user_id, auth_status),
    KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户实名认证记录';
