CREATE TABLE rent_order (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    house_id VARCHAR(36) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pendingRealName',
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    lease_months INT NOT NULL,
    payment_method VARCHAR(30),
    tenant_count INT NOT NULL DEFAULT 1,
    tenant_name VARCHAR(30),
    tenant_phone VARCHAR(20),
    tenant_id_card VARCHAR(30),
    monthly_rent INT NOT NULL,
    deposit INT NOT NULL,
    service_fee INT NOT NULL DEFAULT 0,
    first_payment_amount INT NOT NULL,
    total_amount INT NOT NULL,
    real_name_at TIMESTAMP NULL,
    contract_confirmed_at TIMESTAMP NULL,
    paid_at TIMESTAMP NULL,
    signed_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    INDEX idx_rent_order_user (user_id, status),
    INDEX idx_rent_order_house (house_id)
);

CREATE TABLE rent_contract (
    id VARCHAR(36) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    house_id VARCHAR(36) NOT NULL,
    contract_no VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    tenant_name VARCHAR(30) NOT NULL,
    tenant_phone VARCHAR(20) NOT NULL,
    tenant_id_card VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    lease_months INT NOT NULL,
    monthly_rent INT NOT NULL,
    deposit INT NOT NULL,
    service_fee INT NOT NULL DEFAULT 0,
    house_name VARCHAR(200),
    room_name VARCHAR(100),
    house_address VARCHAR(500),
    signed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_rent_contract_no UNIQUE (contract_no),
    INDEX idx_rent_contract_order (order_id),
    INDEX idx_rent_contract_user (user_id)
);
